import './globals.css';
import Image from 'next/image';
import localFont from 'next/font/local';
import Link from 'next/link';
import CartLink from './components/CartLink';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: {
    default: 'Home | Pawfect Pet Store',
    template: '%s | Pawfect Pet Store',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <div className="header__logo">
            <Link href="/">
              <Image src="/logo.svg" alt="UpLeveled" height={80} width={150} />
            </Link>
          </div>
          <nav className='nav-bar'>
            <Link href="/" className="nav__link">Home</Link>
            <Link href="/products" data-test-id="products-link" className="nav__link">Products</Link>
            <CartLink />
            <Link href="/checkout" className="nav__link">Checkout</Link>
          </nav>
        </header>
        <main className="main">{children}</main>
        <footer className="footer">
          Disclaimer: This is a student project for learning purposes only. The products and images displayed are not owned by me and are not available for purchase.
        </footer>
      </body>
    </html>
  );
}
