
import Image from 'next/image';
import Link from 'next/link';
import { getProducts } from '../../database/products';

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
};


export default function ProductsPage() {
  const products = getProducts();
  return(
    <div>
    <h1>Products :D</h1>
    {products.map((product) => {
      return (
      <div key={`products-${product.id}`}>
      <Link href={`/products/${product.id}`}>
      <div>{product.name}</div>
      <Image src={`/images/${product.name.toLowerCase()}.svg`} alt={product.name}
      height={250}
      width={350} />
      </ Link>
    </div>
    )})}
    </div>
    )
}
